
spring:
  application:
    name: AGENT-SERVICE

eureka:
  client:
    service-url:
      defaultZone: https://registry-service.azurewebsites.net/eureka/
  instance:
    preferIpAddress: true


#eureka:
#  client:
#    serviceUrl:
#
#      defaultZone: http://localhost:8761/eureka/
##      defaultZone:  https://registry-microservice.herokuapp.com/eureka/
##  instance:
##    preferIpAdress: true

